language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=dev-master

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

notifications:
    webhooks: http://sonata-project.org/bundles/user/master/travis

matrix:
  allow_failures:
    - php: hhvm
